version: '3.9'

services:
  frontend:
    image: cl-frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
    deploy: 
      placement: 
        constraints: [ node.role == worker ]
      replicas: 4
      mode: replicated

  backend:
    image: cl-backend
    ports:
      - 3000:3000
    depends_on:
      - db
    deploy: 
      placement: 
        constraints: [ node.role == worker ]
      replicas: 4
      mode: replicated
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=root
      - DB_PASSWORD=root1234
      - DB_DATABASE=cl-eksamen
      
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=cl-eksamen
    volumes:
      - cl_db:/var/lib/mysql
    deploy: 
      placement: 
        constraints: [ node.role == manager ]

volumes:
  cl_db:
    driver: local